import type { Oppw4Character } from "./index";

export const OPPW4_CHARACTERS: Oppw4Character[] = [
  { slug: "bartolomeo", name: "Bartolomeo", displayName: "Bartolomeo", isDlc: false, pack: "Base roster" },
  { slug: "basil-hawkins", name: "Basil Hawkins", displayName: "Basil Hawkins", isDlc: false, pack: "Base roster" },
  { slug: "boa-hancock", name: "Boa Hancock", displayName: "Boa Hancock", isDlc: false, pack: "Base roster" },
  { slug: "borsalino", name: "Borsalino", displayName: "Borsalino / Kizaru", isDlc: false, pack: "Base roster" },
  { slug: "brook", name: "Brook", displayName: "Brook", isDlc: false, pack: "Base roster" },
  { slug: "buggy", name: "Buggy", displayName: "Buggy", isDlc: false, pack: "Base roster" },
  { slug: "capone-bege", name: "Capone Bege", displayName: "Capone Bege", isDlc: false, pack: "Base roster" },
  { slug: "carrot", name: "Carrot", displayName: "Carrot", isDlc: false, pack: "Base roster" },
  { slug: "cavendish", name: "Cavendish", displayName: "Cavendish", isDlc: false, pack: "Base roster" },
  { slug: "charlotte-katakuri", name: "Charlotte Katakuri", displayName: "Charlotte Katakuri", isDlc: false, pack: "Base roster" },
  { slug: "charlotte-linlin", name: "Charlotte Linlin", displayName: "Big Mom / Charlotte Linlin", isDlc: false, pack: "Base roster" },
  { slug: "crocodile", name: "Crocodile", displayName: "Crocodile", isDlc: false, pack: "Base roster" },
  { slug: "donquixote-doflamingo", name: "Donquixote Doflamingo", displayName: "Donquixote Doflamingo", isDlc: false, pack: "Base roster" },
  { slug: "dracule-mihawk", name: "Dracule Mihawk", displayName: "Dracule Mihawk", isDlc: false, pack: "Base roster" },
  { slug: "edward-newgate", name: "Edward Newgate", displayName: "Whitebeard / Edward Newgate", isDlc: false, pack: "Base roster" },
  { slug: "emporio-ivankov", name: "Emporio Ivankov", displayName: "Emporio Ivankov", isDlc: false, pack: "Base roster" },
  { slug: "eustass-kid", name: "Eustass Kid", displayName: "Eustass Kid", isDlc: false, pack: "Base roster" },
  { slug: "franky", name: "Franky", displayName: "Franky", isDlc: false, pack: "Base roster" },
  { slug: "issho", name: "Issho", displayName: "Fujitora / Issho", isDlc: false, pack: "Base roster" },
  { slug: "jimbei", name: "Jimbei", displayName: "Jimbei", isDlc: false, pack: "Base roster" },
  { slug: "kaido", name: "Kaido", displayName: "Kaido", isDlc: false, pack: "Base roster" },
  { slug: "kuzan", name: "Kuzan", displayName: "Kuzan / Aokiji", isDlc: false, pack: "Base roster" },
  { slug: "marco", name: "Marco", displayName: "Marco", isDlc: false, pack: "Base roster" },
  { slug: "marshall-d-teach", name: "Marshall D. Teach", displayName: "Blackbeard / Marshall D. Teach", isDlc: false, pack: "Base roster" },
  { slug: "monkey-d-luffy", name: "Monkey D. Luffy", displayName: "Monkey D. Luffy", isDlc: false, pack: "Base roster" },
  { slug: "nami", name: "Nami", displayName: "Nami", isDlc: false, pack: "Base roster" },
  { slug: "nico-robin", name: "Nico Robin", displayName: "Nico Robin", isDlc: false, pack: "Base roster" },
  { slug: "portgas-d-ace", name: "Portgas D. Ace", displayName: "Portgas D. Ace", isDlc: false, pack: "Base roster" },
  { slug: "rob-lucci", name: "Rob Lucci", displayName: "Rob Lucci", isDlc: false, pack: "Base roster" },
  { slug: "roronoa-zoro", name: "Roronoa Zoro", displayName: "Roronoa Zoro", isDlc: false, pack: "Base roster" },
  { slug: "sabo", name: "Sabo", displayName: "Sabo", isDlc: false, pack: "Base roster" },
  { slug: "sakazuki", name: "Sakazuki", displayName: "Akainu / Sakazuki", isDlc: false, pack: "Base roster" },
  { slug: "sanji", name: "Sanji", displayName: "Sanji", isDlc: false, pack: "Base roster" },
  { slug: "shanks", name: "Shanks", displayName: "Shanks", isDlc: false, pack: "Base roster" },
  { slug: "smoker", name: "Smoker", displayName: "Smoker", isDlc: false, pack: "Base roster" },
  { slug: "tashigi", name: "Tashigi", displayName: "Tashigi", isDlc: false, pack: "Base roster" },
  { slug: "tony-tony-chopper", name: "Tony Tony Chopper", displayName: "Tony Tony Chopper", isDlc: false, pack: "Base roster" },
  { slug: "trafalgar-law", name: "Trafalgar Law", displayName: "Trafalgar Law", isDlc: false, pack: "Base roster" },
  { slug: "usopp", name: "Usopp", displayName: "Usopp", isDlc: false, pack: "Base roster" },
  { slug: "vinsmoke-ichiji", name: "Vinsmoke Ichiji", displayName: "Vinsmoke Ichiji", isDlc: false, pack: "Base roster" },
  { slug: "vinsmoke-niji", name: "Vinsmoke Niji", displayName: "Vinsmoke Niji", isDlc: false, pack: "Base roster" },
  { slug: "vinsmoke-reiju", name: "Vinsmoke Reiju", displayName: "Vinsmoke Reiju", isDlc: false, pack: "Base roster" },
  { slug: "vinsmoke-yonji", name: "Vinsmoke Yonji", displayName: "Vinsmoke Yonji", isDlc: false, pack: "Base roster" },
  { slug: "charlotte-cracker", name: "Charlotte Cracker", displayName: "Charlotte Cracker", isDlc: true, pack: "Character Pack 1" },
  { slug: "charlotte-smoothie", name: "Charlotte Smoothie", displayName: "Charlotte Smoothie", isDlc: true, pack: "Character Pack 1" },
  { slug: "vinsmoke-judge", name: "Vinsmoke Judge", displayName: "Vinsmoke Judge", isDlc: true, pack: "Character Pack 1" },
  { slug: "killer", name: "Killer", displayName: "Killer", isDlc: true, pack: "Character Pack 2" },
  { slug: "x-drake", name: "X. Drake", displayName: "X. Drake", isDlc: true, pack: "Character Pack 2" },
  { slug: "urouge", name: "Urouge", displayName: "Urouge", isDlc: true, pack: "Character Pack 2" },
  { slug: "kinemon", name: "Kin'emon", displayName: "Kin'emon", isDlc: true, pack: "Character Pack 3" },
  { slug: "okiku", name: "Okiku", displayName: "Okiku", isDlc: true, pack: "Character Pack 3" },
  { slug: "kozuki-oden", name: "Kozuki Oden", displayName: "Kozuki Oden", isDlc: true, pack: "Character Pack 3" },
  { slug: "yamato", name: "Yamato", displayName: "Yamato", isDlc: true, pack: "Character Pack 4" },
  { slug: "monkey-d-luffy-onigashima", name: "Monkey D. Luffy (Onigashima Battle)", displayName: "Monkey D. Luffy (Onigashima Battle)", isDlc: true, pack: "Character Pack 4" },
  { slug: "kaido-onigashima", name: "Kaido (Onigashima Battle)", displayName: "Kaido (Onigashima Battle)", isDlc: true, pack: "Character Pack 4" },
  { slug: "uta-film-red", name: "Uta (Film: Red)", displayName: "Uta (Film: Red)", isDlc: true, pack: "Character Pack 5" },
  { slug: "shanks-film-red", name: "Shanks (Film: Red)", displayName: "Shanks (Film: Red)", isDlc: true, pack: "Character Pack 5" },
  { slug: "koby-film-red", name: "Koby (Film: Red)", displayName: "Koby (Film: Red)", isDlc: true, pack: "Character Pack 5" },
  { slug: "gol-d-roger", name: "Gol D. Roger", displayName: "Gol D. Roger", isDlc: true, pack: "Character Pack 6" },
  { slug: "silvers-rayleigh", name: "Silvers Rayleigh", displayName: "Silvers Rayleigh", isDlc: true, pack: "Character Pack 6" },
  { slug: "monkey-d-garp-hero", name: "Monkey D. Garp (Hero of the Marines)", displayName: "Monkey D. Garp (Hero of the Marines)", isDlc: true, pack: "Character Pack 6" },
  { slug: "rob-lucci-cp0", name: "Rob Lucci (CP0)", displayName: "Rob Lucci -CP0-", isDlc: true, pack: "Character Pack 7" },
  { slug: "jewelry-bonney", name: "Jewelry Bonney", displayName: "Bonney / Jewelry Bonney", isDlc: true, pack: "Character Pack 7" },
  { slug: "s-snake", name: "S-Snake", displayName: "S-Snake", isDlc: true, pack: "Character Pack 7" },
  { slug: "enel", name: "Eneru", displayName: "Eneru / Enel", isDlc: true, pack: "Character Pack 8" },
  { slug: "king", name: "King", displayName: "King", isDlc: true, pack: "Character Pack 8" },
  { slug: "z", name: "Z", displayName: "Z", isDlc: true, pack: "Character Pack 8" }
];
